/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorthInMotionRouteImport } from './routes/worth-in-motion'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LmsRouteImport } from './routes/lms'
import { Route as LivingUniversityRouteImport } from './routes/living-university'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnersSchoolsNgosRouteImport } from './routes/partners.schools-ngos'
import { Route as PartnersPilotsRouteImport } from './routes/partners.pilots'
import { Route as PartnersGovernmentRouteImport } from './routes/partners.government'
import { Route as PartnersFacilitatorsRouteImport } from './routes/partners.facilitators'
import { Route as PartnersCorporatesRouteImport } from './routes/partners.corporates'

const WorthInMotionRoute = WorthInMotionRouteImport.update({
  id: '/worth-in-motion',
  path: '/worth-in-motion',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LmsRoute = LmsRouteImport.update({
  id: '/lms',
  path: '/lms',
  getParentRoute: () => rootRouteImport,
} as any)
const LivingUniversityRoute = LivingUniversityRouteImport.update({
  id: '/living-university',
  path: '/living-university',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersSchoolsNgosRoute = PartnersSchoolsNgosRouteImport.update({
  id: '/schools-ngos',
  path: '/schools-ngos',
  getParentRoute: () => PartnersRoute,
} as any)
const PartnersPilotsRoute = PartnersPilotsRouteImport.update({
  id: '/pilots',
  path: '/pilots',
  getParentRoute: () => PartnersRoute,
} as any)
const PartnersGovernmentRoute = PartnersGovernmentRouteImport.update({
  id: '/government',
  path: '/government',
  getParentRoute: () => PartnersRoute,
} as any)
const PartnersFacilitatorsRoute = PartnersFacilitatorsRouteImport.update({
  id: '/facilitators',
  path: '/facilitators',
  getParentRoute: () => PartnersRoute,
} as any)
const PartnersCorporatesRoute = PartnersCorporatesRouteImport.update({
  id: '/corporates',
  path: '/corporates',
  getParentRoute: () => PartnersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/ecosystem': typeof EcosystemRoute
  '/impact': typeof ImpactRoute
  '/insights': typeof InsightsRoute
  '/living-university': typeof LivingUniversityRoute
  '/lms': typeof LmsRoute
  '/marketplace': typeof MarketplaceRoute
  '/partners': typeof PartnersRouteWithChildren
  '/platform': typeof PlatformRoute
  '/worth-in-motion': typeof WorthInMotionRoute
  '/partners/corporates': typeof PartnersCorporatesRoute
  '/partners/facilitators': typeof PartnersFacilitatorsRoute
  '/partners/government': typeof PartnersGovernmentRoute
  '/partners/pilots': typeof PartnersPilotsRoute
  '/partners/schools-ngos': typeof PartnersSchoolsNgosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/ecosystem': typeof EcosystemRoute
  '/impact': typeof ImpactRoute
  '/insights': typeof InsightsRoute
  '/living-university': typeof LivingUniversityRoute
  '/lms': typeof LmsRoute
  '/marketplace': typeof MarketplaceRoute
  '/partners': typeof PartnersRouteWithChildren
  '/platform': typeof PlatformRoute
  '/worth-in-motion': typeof WorthInMotionRoute
  '/partners/corporates': typeof PartnersCorporatesRoute
  '/partners/facilitators': typeof PartnersFacilitatorsRoute
  '/partners/government': typeof PartnersGovernmentRoute
  '/partners/pilots': typeof PartnersPilotsRoute
  '/partners/schools-ngos': typeof PartnersSchoolsNgosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/ecosystem': typeof EcosystemRoute
  '/impact': typeof ImpactRoute
  '/insights': typeof InsightsRoute
  '/living-university': typeof LivingUniversityRoute
  '/lms': typeof LmsRoute
  '/marketplace': typeof MarketplaceRoute
  '/partners': typeof PartnersRouteWithChildren
  '/platform': typeof PlatformRoute
  '/worth-in-motion': typeof WorthInMotionRoute
  '/partners/corporates': typeof PartnersCorporatesRoute
  '/partners/facilitators': typeof PartnersFacilitatorsRoute
  '/partners/government': typeof PartnersGovernmentRoute
  '/partners/pilots': typeof PartnersPilotsRoute
  '/partners/schools-ngos': typeof PartnersSchoolsNgosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/ecosystem'
    | '/impact'
    | '/insights'
    | '/living-university'
    | '/lms'
    | '/marketplace'
    | '/partners'
    | '/platform'
    | '/worth-in-motion'
    | '/partners/corporates'
    | '/partners/facilitators'
    | '/partners/government'
    | '/partners/pilots'
    | '/partners/schools-ngos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/ecosystem'
    | '/impact'
    | '/insights'
    | '/living-university'
    | '/lms'
    | '/marketplace'
    | '/partners'
    | '/platform'
    | '/worth-in-motion'
    | '/partners/corporates'
    | '/partners/facilitators'
    | '/partners/government'
    | '/partners/pilots'
    | '/partners/schools-ngos'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/ecosystem'
    | '/impact'
    | '/insights'
    | '/living-university'
    | '/lms'
    | '/marketplace'
    | '/partners'
    | '/platform'
    | '/worth-in-motion'
    | '/partners/corporates'
    | '/partners/facilitators'
    | '/partners/government'
    | '/partners/pilots'
    | '/partners/schools-ngos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EcosystemRoute: typeof EcosystemRoute
  ImpactRoute: typeof ImpactRoute
  InsightsRoute: typeof InsightsRoute
  LivingUniversityRoute: typeof LivingUniversityRoute
  LmsRoute: typeof LmsRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PartnersRoute: typeof PartnersRouteWithChildren
  PlatformRoute: typeof PlatformRoute
  WorthInMotionRoute: typeof WorthInMotionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worth-in-motion': {
      id: '/worth-in-motion'
      path: '/worth-in-motion'
      fullPath: '/worth-in-motion'
      preLoaderRoute: typeof WorthInMotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lms': {
      id: '/lms'
      path: '/lms'
      fullPath: '/lms'
      preLoaderRoute: typeof LmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/living-university': {
      id: '/living-university'
      path: '/living-university'
      fullPath: '/living-university'
      preLoaderRoute: typeof LivingUniversityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/schools-ngos': {
      id: '/partners/schools-ngos'
      path: '/schools-ngos'
      fullPath: '/partners/schools-ngos'
      preLoaderRoute: typeof PartnersSchoolsNgosRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/partners/pilots': {
      id: '/partners/pilots'
      path: '/pilots'
      fullPath: '/partners/pilots'
      preLoaderRoute: typeof PartnersPilotsRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/partners/government': {
      id: '/partners/government'
      path: '/government'
      fullPath: '/partners/government'
      preLoaderRoute: typeof PartnersGovernmentRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/partners/facilitators': {
      id: '/partners/facilitators'
      path: '/facilitators'
      fullPath: '/partners/facilitators'
      preLoaderRoute: typeof PartnersFacilitatorsRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/partners/corporates': {
      id: '/partners/corporates'
      path: '/corporates'
      fullPath: '/partners/corporates'
      preLoaderRoute: typeof PartnersCorporatesRouteImport
      parentRoute: typeof PartnersRoute
    }
  }
}

interface PartnersRouteChildren {
  PartnersCorporatesRoute: typeof PartnersCorporatesRoute
  PartnersFacilitatorsRoute: typeof PartnersFacilitatorsRoute
  PartnersGovernmentRoute: typeof PartnersGovernmentRoute
  PartnersPilotsRoute: typeof PartnersPilotsRoute
  PartnersSchoolsNgosRoute: typeof PartnersSchoolsNgosRoute
}

const PartnersRouteChildren: PartnersRouteChildren = {
  PartnersCorporatesRoute: PartnersCorporatesRoute,
  PartnersFacilitatorsRoute: PartnersFacilitatorsRoute,
  PartnersGovernmentRoute: PartnersGovernmentRoute,
  PartnersPilotsRoute: PartnersPilotsRoute,
  PartnersSchoolsNgosRoute: PartnersSchoolsNgosRoute,
}

const PartnersRouteWithChildren = PartnersRoute._addFileChildren(
  PartnersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EcosystemRoute: EcosystemRoute,
  ImpactRoute: ImpactRoute,
  InsightsRoute: InsightsRoute,
  LivingUniversityRoute: LivingUniversityRoute,
  LmsRoute: LmsRoute,
  MarketplaceRoute: MarketplaceRoute,
  PartnersRoute: PartnersRouteWithChildren,
  PlatformRoute: PlatformRoute,
  WorthInMotionRoute: WorthInMotionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
